<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/css" href="style.css"?>

<!DOCTYPE university[
<!ELEMENT university (spec)*>
<!ELEMENT spec (name,score,plan,city)>
<!ELEMENT name (#PCDATA)*>
<!ELEMENT score (#PCDATA)*>
<!ELEMENT plan (#PCDATA)*>
<!ELEMENT city (#PCDATA)*>
]>

<!--<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:complexType>
<xs:sequence>
<xs:element name="name" type="xs:string"/>
<xs:element name="score" type="xs:string"/>
<xs:element name="plan" type="xs:string"/>
<xs:element name="city" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:schema>-->

<university >
<spec>
<name>БГТУ</name>
<score>283 балла</score>
<plan>400 человек</plan>
<city> Брест</city>
</spec>
<spec>
<name>МГУ</name>
<score>292 балла</score>
<plan>520 человек</plan>
<city>Могилев</city>
</spec>
</university>